//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CAMERASECURITY_H_
#define _CAMERASECURITY_H_

#include <TinyCLR_Interop.h>
struct Library_CameraSecurity_CameraSecurity_Program
{
    static const int FIELD_STATIC__contador = 0;

    static const int FIELD__camera = 4;
    static const int FIELD__displayT35 = 5;
    static const int FIELD__button = 6;
    static const int FIELD__usbClientDP = 7;
    static const int FIELD__actualPicture = 8;
    static const int FIELD__pictures = 9;


    //--//

};

struct Library_CameraSecurity_CameraSecurity_Resources
{
    static const int FIELD_STATIC__manager = 1;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CameraSecurity;

#endif  //_CAMERASECURITY_H_
